### ISSUE TITLE
Hash function is called before transformation

### ISSUE THREAD

**Issue by niksy** [geut/postcss-copy#49]
If you want to use special transforms on file like image minification in your example, hash function will be used on original buffer, not on buffer which has been transformed (i.e. minified in this example).

Returning file meta with `hash` property changed also doesn’t do anything.

Is this by design? Am I doing something wrong?

**Comment by tinchoz49** [comment]
Hi niksy!

Yes, the hash property is created using the original buffer. Do you need a hash based on the transform content?

**Comment by niksy** [comment]
That would be preferable. If I'm modifying image buffer, I would expect to have hash based on final buffer.

I think that makes most sense in terms of e.g. proper file revving. What do you think?

**Comment by tinchoz49** [comment]
yes, i think is a good feature

**Comment by tinchoz49** [comment]
working on it

**Comment by tinchoz49** [comment]
done!

**Comment by niksy** [comment]
@tinchoz49 hm, this still doesn’t work as it should, you’re calling hash function on original buffer, not the one returned from transform function: https://github.com/geut/postcss-copy/blob/master/src/index.js#L135-L141

**Comment by tinchoz49** [comment]
yes it's true and there was other issues related with the concurrent process of the files. I fixed it too

**Comment by tinchoz49** [comment]
when you have time, tell me if it works for you :smile:
